### ISSUE TITLE
[GTCEu.lang] 微妙な訳について

### ISSUE THREAD

**Issue by Quarri6343** [MrKono/GregTechCommunityEdition-Japanese#1]
GTCEu_ja_jp.zipをゲーム内で利用するにあたり、未翻訳の物を除いて個人的に微妙な訳がいくつかあったので、ここに報告させて頂きます。
バージョン：22.02.02

・Branch Cutter : 枝切りばさみr => 余分なrがある
・Sense : 鎌 => tooltipに "Because  a scythe doesn't make sense" と鎌(Scythe)ではないことが明記されているが、鎌と翻訳されている
・Plunger : プランジャー => 日本語ではよくラバーカップと呼ばれる
https://ja.wikipedia.org/wiki/ラバーカップ
・Duranium : ドゥラニウム => 元ネタであるスタートレックの界隈ではデュラニウムと呼ばれているので、そちらの方が適切であると考えられる
・Enriched Naquadah Trinium Europium Duranide : 濃縮ナクアダ-トリニウム-ユーロピウム ドゥラニウム化物=>同上
・Manganese Phosphide : りん化マンガン => リン化インジウムガリウムや二リン化三カルシウムで使われている「リン」の表記ゆれ
・Uranium Rhodium Dinaquadide : ウランーロジウム 二ナクアダ物 => oxideが酸化物と訳されているので、二ナクアダ物は二ナクアダ化物と訳すべきと考えられる
・Ethyl Tert-Butyl Ether : エチル-tert-ブチルエステル =>フォーマットコードが指定されているためかと思われるがゲーム内での表記が白くなっている
・Ruby Slurry : ルビー泥 => slurryは日本語ではよく泥漿と呼ばれる(泥ではない)、
Sapphire Slurry、Green Sapphire Slurryについても同様
https://ja.wikipedia.org/wiki/泥漿
・Cupronickel Credit : キュプロニッケルコイル製コイン => キュプロニッケルコイルは電気高炉に用いられるコイルであり、コインの原材料ではない
・Low Voltage Coil : (tooltip)基本的なのコイル => 基本的なコイル
・Compressed Clay : 圧縮粘度 => 圧縮粘土
・Sticky Resin : ゴム => 訳はあっているが、gregtechの別のマテリアルであるRubberと名前が被っていてややこしいので粘着樹脂など適当な名前に変えた方がいいと考えられる
・Advanced SMD ~ : より良いSMD => 他の訳ではAdvancedは発展型と訳されているので違和感がある
・Small Steam Solid Fuel Boiler : 小型石炭ボイラー =>アップデートで名称が「小型固形燃料蒸気ボイラー」に変わっている、
High Pressure Steam Solid Fuel Boiler, Small Steam Liquid Boiler, High Pressure Steam Liquid Boilerについても同様
・High Pressure Steam Compressor : (tooltip)=アイテムを圧縮 => 余分な「=」がある
・Block Breaker : (tooltip) 正面のブロックを破壊し、集める/n稼働にはレッドストーン信号が必要 =>改行(/n)に失敗して余計な「/n」が含まれている
・Arc Furnace : (tooltip) 高炉が必要な人？ => 原文 Who needs a Blast Furnace? は「高炉が必要な人、この世に存在する？」を転じて「(これさえあれば)高炉なんていらない」という意味であると思われる
・Canning Machine : (tooltip) 容器から液体を出し入れ. 今アイテムで! =>原文は「液体を容器に出し入れする. 今回はアイテムにも対応！」のような意味であると思われる
(旧GregtechではFluid Canning Machine と Canning Machineが別の機械であったことを踏まえたtooltip)
・Distillery : (tooltip) 液体の最も関連性のある部分を蒸留する => 原文は「液体の最も適切な部分を蒸留する」のような意味であると思われる
・Creative Quantum Chest : (tooltip)Creative mode のみ => 原文はMachine Hullのtooltipのセルフパロディなので、Machine Hullの日本語訳にならって「使うには ク リ エ イ テ ィ ブ モ ー ド (7色) が必要です.」とした方が違和感が少ない。他のクリエイティブアイテムに関しても同様。
・鉱石タブ : (tooltip) 上層の鉱石 鉱脈の上4に生成される =>上4層に生成される

**Comment by MrKono** [comment]
ありがとうございます。
Ethyl Tert-Butyl Ether以外に対応しました。
Ethyl Tert-Butyl Etherですが、UntranslatedItems等のアイテム名を英語にするmod併用時に該当の現象が起きます。併用しない場合は起きません。現在検討中です。
