### ISSUE TITLE
翻訳の配布方法について

### ISSUE THREAD

**Issue by tier940** [MrKono/GregTechCommunityEdition-Japanese#2]
現状リソースパックにて配布しているとのことですが、この状態ですと色や特殊文字、その他に想定外の挙動をするため下記で使用するように案内した方が良い。
![image](https://user-images.githubusercontent.com/11691836/152931319-b6f5004c-a26c-4a0f-a2e9-8bf101c4f056.png)
https://www.curseforge.com/minecraft/mc-mods/resource-loader

**Comment by MrKono** [comment]
ご指摘ありがとうございます。
README.mdに追記しました。
